### ISSUE TITLE
rosnode kill will not run in the shutdown script

### ISSUE THREAD

**Issue by moorepants** [mechmotum/BicycleDataLogger#2]
Eddie's question:

https://unix.stackexchange.com/questions/464212/why-cant-i-kill-ros-nodes-through-a-shell-script

Also:
https://stackoverflow.com/help/how-to-ask

**Comment by moorepants** [comment]
You got it working??

**Comment by EDJ14** [comment]
Yes! A couple of the grad students in Professor Kong's lab were able to
help me finally resolve it.
